version: '3.4'

services:
  api_netcore:
    image: api_netcore
    build: 
      context: .
      dockerfile: ./BackendNet/Dockerfile
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./Hls_video:/app/wwwroot
    # develop:
    #   watch:
    #     - action: rebuild
    #     - path: .
    # depends_on:
    #   - mongodb
  
  fastapi:
    image: fastapi
    build: 
      context: ./Python   
    ports:
      - "800:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  nginx_rtmp_server:
    image: nginx_rtmp_server
    build: 
      context: .
      dockerfile: ./rtmp/Dockerfile
    ports:
      - 1935:1935
      - 8000:8000
    volumes:
      - ./Hls_video:/tmp/hls

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #   volumes:
  #     - ./database-data:/data/db
  
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #   - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongodb:27017/
  #     - ME_CONFIG_BASICAUTH_USERNAME=root
  #     - ME_CONFIG_BASICAUTH_PASSWORD=password
